Algoritmo "Conta pra tras"
// Algoritmos
// Gustavo Guanabara 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/10/2022
Var
// Seção de Declarações das variáveis 
   c : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

   para c <- 100 ate 0 passo -10 faca
        escreva(c)
   fimpara
   
   escreva(" Acabou!")


Fimalgoritmo