algoritmo "O dobro e a terça parte"
// Função : O dobro ea terça parte de um número
// Autor :Lohan Souza de Oliveira
// Data : 21/09/2022
// Seção de Declarações 
var
   n, dobro, terca : real
inicio
// Seção de Comandos
   Escreval("Digire um número: ")
   leia(n)
   
   dobro <- n * 2
   terca <- n / 3
   
   escreval("O dobro de", n, " é", dobro)
   escreval("A terça parte de", n, " é", terca:5:2)

fimalgoritmo
