Algoritmo "semnome"
// Disciplina: Curso de algoritmos
// Professor: Gustavo Guanabara 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/10/2022
Var
// Seção de Declarações das variáveis 
 n : vetor [1..7] de inteiro
 c : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   para c <- 1 ate 7 faca
        aleatorio 0, 100
        leia(n[c])
        aleatorio off
   fimpara


Fimalgoritmo