Algoritmo "para contar"
// Algoritmos
// Gustavo Guanabara 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/10/2022
Var
// Seção de Declarações das variáveis 
   c : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   
   para c <- 0 ate 40 passo 5 faca
        escreva(c)
   fimpara
   
   escreva(" Acabou!")


Fimalgoritmo