Algoritmo "tabuada"
// Algoritmos
// Gustavo Guanabara 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/10/2022
Var
// Seção de Declarações das variáveis 
   num, t, m : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

   escreval("Digite um número: ")
   leia(num)

   para t <- 1 ate 10 faca
        m <- num * t
        escreval(num, " X", t, " =", m)
   fimpara



Fimalgoritmo