Algoritmo "semnome"
// Algoritmos
// Gustavo Guanabara 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/10/2022
Var
// Seção de Declarações das variáveis 
   n : vetor [0..7] de inteiro
   c : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...



   para c <- 0 ate 7 faca
        n[c] <- 999
        escreva(n[c])
   fimpara

Fimalgoritmo