Algoritmo "contador"
// Disciplina: Curso de algoritmos
// Professor: Gustavo Guanabara 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/10/2022
Var
// Seção de Declarações das variáveis 
   c, n : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

   escreval("Digite um número: ")
   leia(n)

   para c <- 0 ate n faca
        escreva(c)
   fimpara
   
   escreva(" FIM!")


Fimalgoritmo