Algoritmo "semnome"
// Algoritmos
// Gustavo Guanabara 
// Descrição   : Mensagem de Boas Vindas
// Autor(a)    : Lohan Souza de Oliveira
// Data atual  : 21/09/2022
Var
// Seção de Declarações das variáveis 
   nome : caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreval ("Qual é o seu nome? ")
   leia (nome)
   
   escreval ("Olá ", nome, " é um prazer te conhecer!")

Fimalgoritmo