Algoritmo "Somador"
// Algoritmos
// Gustavo Guanabara 
// Descrição   : Soma os numeros
// Autor(a)    : Lohan Souza de Oliveira
// Data atual  : 05/10/2022
Var
// Seção de Declarações das variáveis 
   s, N : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

   s <- 0
   
   repita
         escreva("Digite um número: ")
         leia(N)
         escreval(N)
         s <- s + N
   ate (N = 1111)
   
   escreval("A soma entre esses numeros é:", s)


Fimalgoritmo