algoritmo "Média"
// Função : Media de disciplina
// Autor : Lohan Souza de Oliveira
// Data : 21/09/2022
// Seção de Declarações 
var
   n1, n2, media : real
inicio
// Seção de Comandos 
   escreval("Digite a primeira nota: ")
   leia(n1)
   escreval("Digite a segunda nota: ")
   leia(n2)
   
   media <- (n1 + n2) / 2
   
   escreval("A média entre", n1, " e", n2, " é igual a ", media:2:2)
fimalgoritmo
