Algoritmo "semnome"
// Algoritmos
// Gustavo Guanabara 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/10/2022
Var
// Seção de Declarações das variáveis 
   cont : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   enquanto (cont <= 30) faca
            escreva(cont)
            
            cont <- cont + 3
   fimenquanto
   
   escreva(" Acabou!")


Fimalgoritmo